In [1]:
print("Hello World")

Hello World


In [2]:
class Employee:
    def __init__(self,name,age,salary,ids):
        self.name = name
        self.age = age
        self.salary = salary
        self.id = ids
EmployeeDetails = Employee("UA",21,2500000,27)
print(EmployeeDetails.name,"")
print(EmployeeDetails.age," ")
print(EmployeeDetails.salary,"")
print(EmployeeDetails.id,"")

UA 
21  
2500000 
27 


In [3]:
import numpy as np
import pandas as pd
dic1 = {
    "name":["Utkrist","Iker Casillas","CR7","LM10"],
    "JerseyNumber":[27,1,7,10],
    "Country":["India","Spain","Portugal","Argentina"]
}
DF = pd.DataFrame(dic1)
print(DF)  

            name  JerseyNumber    Country
0        Utkrist            27      India
1  Iker Casillas             1      Spain
2            CR7             7   Portugal
3           LM10            10  Argentina


In [4]:
DF.to_csv('players1.csv', index=False)

In [5]:
DF.head(2)

name  JerseyNumber Country
0        Utkrist            27   India
1  Iker Casillas             1   Spain

In [6]:
DF.tail(0)

Empty DataFrame
Columns: [name, JerseyNumber, Country]
Index: []

In [7]:
DF.describe()

JerseyNumber
count      4.000000
mean      11.250000
std       11.146748
min        1.000000
25%        5.500000
50%        8.500000
75%       14.250000
max       27.000000

In [8]:
import pandas

Dic1 = {
    "StudentName": ["David Villa", "Iker Casillas", "Cristiano Ronaldo", "Lionel Messi", "Neymar JR", "Kylian Mbappe",
                    "Khvicha Kvaratskhelia"],
    "Position": ["LWF,RWF,CF,SS", "GK", "LWF/ST/CF", "RWF,CAM,CF", "CAM,LWF,SS", "CF,LWF,RWF", "LWF,RWF"],
    "BirthCountry": ["Spain", "Spain", "Portugal", "Argentina", "Brazil", "France", "Georgia"],
    "PlayingCountry": ["Retired", "Retired", "Saudi Arabia", "France", "France", "France", "Italy"],
    "Salary": ["$50 Millions", "$38 Millions", "$500 Millions", "$435 Millions", "$128 Millions", "$222 Millions",
               "$46 "
               "Millions"]
}
Df = pandas.DataFrame(Dic1)
Df.to_csv('playersDetails.csv')
Df.to_html('players.html', index=False)
# print(Dic1)


In [9]:
Df.describe()


StudentName       Position BirthCountry PlayingCountry        Salary
count             7              7            7              7             7
unique            7              7            6              4             7
top     David Villa  LWF,RWF,CF,SS        Spain         France  $50 Millions
freq              1              1            2              3             1

In [10]:
PlayerDetails = pandas.read_csv('playersDetails.csv')

In [11]:
Df.index = ["one","two","Three","Four","Five","Sixth","Seventh"]

In [12]:
Df

StudentName       Position BirthCountry PlayingCountry  \
one                David Villa  LWF,RWF,CF,SS        Spain        Retired   
two              Iker Casillas             GK        Spain        Retired   
Three        Cristiano Ronaldo      LWF/ST/CF     Portugal   Saudi Arabia   
Four              Lionel Messi     RWF,CAM,CF    Argentina         France   
Five                 Neymar JR     CAM,LWF,SS       Brazil         France   
Sixth            Kylian Mbappe     CF,LWF,RWF       France         France   
Seventh  Khvicha Kvaratskhelia        LWF,RWF      Georgia          Italy   

                Salary  
one       $50 Millions  
two       $38 Millions  
Three    $500 Millions  
Four     $435 Millions  
Five     $128 Millions  
Sixth    $222 Millions  
Seventh   $46 Millions

In [13]:
import numpy
ser = pandas.Series(numpy.random.rand(10))
ser

0    0.988038
1    0.220812
2    0.728368
3    0.221888
4    0.338799
5    0.007992
6    0.671873
7    0.217006
8    0.842654
9    0.790199
dtype: float64

In [14]:
type(ser)

pandas.core.series.Series

In [15]:
newDf = pandas.DataFrame(numpy.random.rand(34,5))
newDf

0         1         2         3         4
0   0.078495  0.463944  0.208102  0.554785  0.251085
1   0.368510  0.767073  0.741430  0.611779  0.559618
2   0.525879  0.824521  0.262539  0.329309  0.874481
3   0.543962  0.388928  0.335801  0.777046  0.522896
4   0.924723  0.826409  0.889097  0.517515  0.649117
5   0.884316  0.446076  0.022454  0.134607  0.406615
6   0.442676  0.611115  0.180099  0.423219  0.547070
7   0.137141  0.978903  0.666926  0.351427  0.812804
8   0.290511  0.507438  0.709524  0.682470  0.932833
9   0.663006  0.369717  0.133678  0.900108  0.600276
10  0.233573  0.751243  0.680852  0.690703  0.295929
11  0.976857  0.363559  0.858902  0.005269  0.417918
12  0.510970  0.597602  0.072590  0.551068  0.810758
13  0.845175  0.586983  0.376688  0.719509  0.868048
14  0.087379  0.215937  0.431374  0.678564  0.030976
15  0.952579  0.449171  0.856842  0.062706  0.660881
16  0.340045  0.932221  0.420739  0.026452  0.316419
17  0.183184  0.788428  0.465739  0.173525  0.804952
18  0.951850  0.765132  0.885801  0.253438  0.880894
19  0.456648  0.059460  0.666379  0.493071  0.965852
20  0.523275  0.985630  0.998574  0.160074  0.092825
21  0.176071  0.477443  0.311376  0.804201  0.417940
22  0.295377  0.933568  0.256403  0.386335  0.049621
23  0.414348  0.431303  0.588481  0.901976  0.270217
24  0.339938  0.301998  0.057615  0.751375  0.042181
25  0.473987  0.046070  0.024835  0.929161  0.173145
26  0.833825  0.598917  0.628895  0.705950  0.365795
27  0.616065  0.150301  0.856645  0.727908  0.661131
28  0.167745  0.196162  0.622460  0.590986  0.342853
29  0.808156  0.637479  0.299599  0.723267  0.176926
30  0.001424  0.565537  0.003371  0.288216  0.831933
31  0.746669  0.080857  0.457038  0.457863  0.975930
32  0.525459  0.260062  0.318291  0.659480  0.152833
33  0.375850  0.310865  0.518755  0.839724  0.804711

In [16]:
newDf.head(9)


0         1         2         3         4
0  0.078495  0.463944  0.208102  0.554785  0.251085
1  0.368510  0.767073  0.741430  0.611779  0.559618
2  0.525879  0.824521  0.262539  0.329309  0.874481
3  0.543962  0.388928  0.335801  0.777046  0.522896
4  0.924723  0.826409  0.889097  0.517515  0.649117
5  0.884316  0.446076  0.022454  0.134607  0.406615
6  0.442676  0.611115  0.180099  0.423219  0.547070
7  0.137141  0.978903  0.666926  0.351427  0.812804
8  0.290511  0.507438  0.709524  0.682470  0.932833

In [17]:
type(newDf)

pandas.core.frame.DataFrame

In [18]:
newDf.index

RangeIndex(start=0, stop=34, step=1)

In [19]:
newDf.columns

RangeIndex(start=0, stop=5, step=1)

In [20]:
newDf.to_numpy()

array([[0.07849452, 0.46394407, 0.20810177, 0.55478538, 0.25108467],
       [0.36851004, 0.76707345, 0.74142969, 0.61177869, 0.5596176 ],
       [0.52587894, 0.82452088, 0.26253902, 0.32930893, 0.87448131],
       [0.54396207, 0.3889278 , 0.33580117, 0.77704588, 0.52289553],
       [0.92472287, 0.82640944, 0.88909667, 0.5175147 , 0.64911665],
       [0.8843159 , 0.44607593, 0.02245386, 0.1346071 , 0.40661478],
       [0.44267647, 0.61111492, 0.18009897, 0.42321937, 0.54707014],
       [0.13714126, 0.97890328, 0.66692589, 0.35142662, 0.81280445],
       [0.2905113 , 0.50743813, 0.70952427, 0.68247002, 0.93283318],
       [0.66300605, 0.36971748, 0.13367803, 0.90010762, 0.60027648],
       [0.23357274, 0.75124267, 0.68085206, 0.69070284, 0.29592929],
       [0.97685717, 0.3635586 , 0.85890159, 0.00526872, 0.41791785],
       [0.51097007, 0.59760217, 0.07259024, 0.5510678 , 0.81075812],
       [0.84517478, 0.5869826 , 0.37668814, 0.71950895, 0.86804791],
       [0.08737871, 0.21593722, 0.

In [21]:
newDf.T

0         1         2         3         4         5         6   \
0  0.078495  0.368510  0.525879  0.543962  0.924723  0.884316  0.442676   
1  0.463944  0.767073  0.824521  0.388928  0.826409  0.446076  0.611115   
2  0.208102  0.741430  0.262539  0.335801  0.889097  0.022454  0.180099   
3  0.554785  0.611779  0.329309  0.777046  0.517515  0.134607  0.423219   
4  0.251085  0.559618  0.874481  0.522896  0.649117  0.406615  0.547070   

         7         8         9   ...        24        25        26        27  \
0  0.137141  0.290511  0.663006  ...  0.339938  0.473987  0.833825  0.616065   
1  0.978903  0.507438  0.369717  ...  0.301998  0.046070  0.598917  0.150301   
2  0.666926  0.709524  0.133678  ...  0.057615  0.024835  0.628895  0.856645   
3  0.351427  0.682470  0.900108  ...  0.751375  0.929161  0.705950  0.727908   
4  0.812804  0.932833  0.600276  ...  0.042181  0.173145  0.365795  0.661131   

         28        29        30        31        32        33  
0  0.167745  0.808156  0.001424  0.746669  0.525459  0.375850  
1  0.196162  0.637479  0.565537  0.080857  0.260062  0.310865  
2  0.622460  0.299599  0.003371  0.457038  0.318291  0.518755  
3  0.590986  0.723267  0.288216  0.457863  0.659480  0.839724  
4  0.342853  0.176926  0.831933  0.975930  0.152833  0.804711  

[5 rows x 34 columns]

In [22]:
newDf.sort_index(axis=0,ascending=False)

0         1         2         3         4
33  0.375850  0.310865  0.518755  0.839724  0.804711
32  0.525459  0.260062  0.318291  0.659480  0.152833
31  0.746669  0.080857  0.457038  0.457863  0.975930
30  0.001424  0.565537  0.003371  0.288216  0.831933
29  0.808156  0.637479  0.299599  0.723267  0.176926
28  0.167745  0.196162  0.622460  0.590986  0.342853
27  0.616065  0.150301  0.856645  0.727908  0.661131
26  0.833825  0.598917  0.628895  0.705950  0.365795
25  0.473987  0.046070  0.024835  0.929161  0.173145
24  0.339938  0.301998  0.057615  0.751375  0.042181
23  0.414348  0.431303  0.588481  0.901976  0.270217
22  0.295377  0.933568  0.256403  0.386335  0.049621
21  0.176071  0.477443  0.311376  0.804201  0.417940
20  0.523275  0.985630  0.998574  0.160074  0.092825
19  0.456648  0.059460  0.666379  0.493071  0.965852
18  0.951850  0.765132  0.885801  0.253438  0.880894
17  0.183184  0.788428  0.465739  0.173525  0.804952
16  0.340045  0.932221  0.420739  0.026452  0.316419
15  0.952579  0.449171  0.856842  0.062706  0.660881
14  0.087379  0.215937  0.431374  0.678564  0.030976
13  0.845175  0.586983  0.376688  0.719509  0.868048
12  0.510970  0.597602  0.072590  0.551068  0.810758
11  0.976857  0.363559  0.858902  0.005269  0.417918
10  0.233573  0.751243  0.680852  0.690703  0.295929
9   0.663006  0.369717  0.133678  0.900108  0.600276
8   0.290511  0.507438  0.709524  0.682470  0.932833
7   0.137141  0.978903  0.666926  0.351427  0.812804
6   0.442676  0.611115  0.180099  0.423219  0.547070
5   0.884316  0.446076  0.022454  0.134607  0.406615
4   0.924723  0.826409  0.889097  0.517515  0.649117
3   0.543962  0.388928  0.335801  0.777046  0.522896
2   0.525879  0.824521  0.262539  0.329309  0.874481
1   0.368510  0.767073  0.741430  0.611779  0.559618
0   0.078495  0.463944  0.208102  0.554785  0.251085

In [23]:
newDf.T

0         1         2         3         4         5         6   \
0  0.078495  0.368510  0.525879  0.543962  0.924723  0.884316  0.442676   
1  0.463944  0.767073  0.824521  0.388928  0.826409  0.446076  0.611115   
2  0.208102  0.741430  0.262539  0.335801  0.889097  0.022454  0.180099   
3  0.554785  0.611779  0.329309  0.777046  0.517515  0.134607  0.423219   
4  0.251085  0.559618  0.874481  0.522896  0.649117  0.406615  0.547070   

         7         8         9   ...        24        25        26        27  \
0  0.137141  0.290511  0.663006  ...  0.339938  0.473987  0.833825  0.616065   
1  0.978903  0.507438  0.369717  ...  0.301998  0.046070  0.598917  0.150301   
2  0.666926  0.709524  0.133678  ...  0.057615  0.024835  0.628895  0.856645   
3  0.351427  0.682470  0.900108  ...  0.751375  0.929161  0.705950  0.727908   
4  0.812804  0.932833  0.600276  ...  0.042181  0.173145  0.365795  0.661131   

         28        29        30        31        32        33  
0  0.167745  0.808156  0.001424  0.746669  0.525459  0.375850  
1  0.196162  0.637479  0.565537  0.080857  0.260062  0.310865  
2  0.622460  0.299599  0.003371  0.457038  0.318291  0.518755  
3  0.590986  0.723267  0.288216  0.457863  0.659480  0.839724  
4  0.342853  0.176926  0.831933  0.975930  0.152833  0.804711  

[5 rows x 34 columns]

In [24]:
import pandas
import numpy
newDf1 = pandas.DataFrame(numpy.random.rand(10,5))
newDf1

0         1         2         3         4
0  0.898509  0.779575  0.550535  0.004073  0.835947
1  0.750831  0.016320  0.799095  0.359194  0.904489
2  0.615414  0.635965  0.429532  0.499447  0.103171
3  0.774035  0.813879  0.507878  0.405821  0.840531
4  0.295717  0.605386  0.972121  0.126850  0.792573
5  0.720170  0.821819  0.928974  0.767605  0.514593
6  0.602202  0.000999  0.424780  0.605551  0.625111
7  0.151765  0.301698  0.723679  0.354974  0.052045
8  0.291905  0.895807  0.603437  0.981868  0.352869
9  0.020771  0.368341  0.766077  0.924654  0.741197

In [25]:
newDf1.loc[0,0] = 1432543545
newDf1.head(2)

0         1         2         3         4
0  1.432544e+09  0.779575  0.550535  0.004073  0.835947
1  7.508306e-01  0.016320  0.799095  0.359194  0.904489

In [26]:
newDf1.columns = list("ABCDE")
newDf1

A         B         C         D         E
0  1.432544e+09  0.779575  0.550535  0.004073  0.835947
1  7.508306e-01  0.016320  0.799095  0.359194  0.904489
2  6.154135e-01  0.635965  0.429532  0.499447  0.103171
3  7.740347e-01  0.813879  0.507878  0.405821  0.840531
4  2.957165e-01  0.605386  0.972121  0.126850  0.792573
5  7.201702e-01  0.821819  0.928974  0.767605  0.514593
6  6.022022e-01  0.000999  0.424780  0.605551  0.625111
7  1.517646e-01  0.301698  0.723679  0.354974  0.052045
8  2.919052e-01  0.895807  0.603437  0.981868  0.352869
9  2.077120e-02  0.368341  0.766077  0.924654  0.741197

In [27]:
newDf1.loc[0,'A'] = 563432
newDf1

A         B         C         D         E
0  563432.000000  0.779575  0.550535  0.004073  0.835947
1       0.750831  0.016320  0.799095  0.359194  0.904489
2       0.615414  0.635965  0.429532  0.499447  0.103171
3       0.774035  0.813879  0.507878  0.405821  0.840531
4       0.295717  0.605386  0.972121  0.126850  0.792573
5       0.720170  0.821819  0.928974  0.767605  0.514593
6       0.602202  0.000999  0.424780  0.605551  0.625111
7       0.151765  0.301698  0.723679  0.354974  0.052045
8       0.291905  0.895807  0.603437  0.981868  0.352869
9       0.020771  0.368341  0.766077  0.924654  0.741197

In [28]:
newDf1.head(5)

A         B         C         D         E
0  563432.000000  0.779575  0.550535  0.004073  0.835947
1       0.750831  0.016320  0.799095  0.359194  0.904489
2       0.615414  0.635965  0.429532  0.499447  0.103171
3       0.774035  0.813879  0.507878  0.405821  0.840531
4       0.295717  0.605386  0.972121  0.126850  0.792573

In [29]:
newDf1.loc[[1,2,4],['A','E']]

A         E
1  0.750831  0.904489
2  0.615414  0.103171
4  0.295717  0.792573

In [30]:
newDf1.loc[:,["A","B"]] #for all columns

A         B
0  563432.000000  0.779575
1       0.750831  0.016320
2       0.615414  0.635965
3       0.774035  0.813879
4       0.295717  0.605386
5       0.720170  0.821819
6       0.602202  0.000999
7       0.151765  0.301698
8       0.291905  0.895807
9       0.020771  0.368341

In [31]:
newDf1.loc[[1,2],:] #for all rows

A         B         C         D         E
1  0.750831  0.016320  0.799095  0.359194  0.904489
2  0.615414  0.635965  0.429532  0.499447  0.103171

In [32]:
newDf1.loc[(newDf1['A']<0.3) & (newDf1['C']>0.3)]

A         B         C         D         E
4  0.295717  0.605386  0.972121  0.126850  0.792573
7  0.151765  0.301698  0.723679  0.354974  0.052045
8  0.291905  0.895807  0.603437  0.981868  0.352869
9  0.020771  0.368341  0.766077  0.924654  0.741197

In [33]:
newDf1.iloc[1,2]

0.7990946730020416

In [34]:
newDf1.iloc[[1,2],[3,2]]

D         C
1  0.359194  0.799095
2  0.499447  0.429532

In [35]:
newDf1.head()

A         B         C         D         E
0  563432.000000  0.779575  0.550535  0.004073  0.835947
1       0.750831  0.016320  0.799095  0.359194  0.904489
2       0.615414  0.635965  0.429532  0.499447  0.103171
3       0.774035  0.813879  0.507878  0.405821  0.840531
4       0.295717  0.605386  0.972121  0.126850  0.792573

In [36]:
newDf1.drop([2])

A         B         C         D         E
0  563432.000000  0.779575  0.550535  0.004073  0.835947
1       0.750831  0.016320  0.799095  0.359194  0.904489
3       0.774035  0.813879  0.507878  0.405821  0.840531
4       0.295717  0.605386  0.972121  0.126850  0.792573
5       0.720170  0.821819  0.928974  0.767605  0.514593
6       0.602202  0.000999  0.424780  0.605551  0.625111
7       0.151765  0.301698  0.723679  0.354974  0.052045
8       0.291905  0.895807  0.603437  0.981868  0.352869
9       0.020771  0.368341  0.766077  0.924654  0.741197

In [37]:
newDf1.drop(['A'],axis = 1,inplace = True)

In [38]:
newDf1.reset_index()

index         B         C         D         E
0      0  0.779575  0.550535  0.004073  0.835947
1      1  0.016320  0.799095  0.359194  0.904489
2      2  0.635965  0.429532  0.499447  0.103171
3      3  0.813879  0.507878  0.405821  0.840531
4      4  0.605386  0.972121  0.126850  0.792573
5      5  0.821819  0.928974  0.767605  0.514593
6      6  0.000999  0.424780  0.605551  0.625111
7      7  0.301698  0.723679  0.354974  0.052045
8      8  0.895807  0.603437  0.981868  0.352869
9      9  0.368341  0.766077  0.924654  0.741197

In [39]:
newDf1.head()

B         C         D         E
0  0.779575  0.550535  0.004073  0.835947
1  0.016320  0.799095  0.359194  0.904489
2  0.635965  0.429532  0.499447  0.103171
3  0.813879  0.507878  0.405821  0.840531
4  0.605386  0.972121  0.126850  0.792573

In [40]:
newDf1

B         C         D         E
0  0.779575  0.550535  0.004073  0.835947
1  0.016320  0.799095  0.359194  0.904489
2  0.635965  0.429532  0.499447  0.103171
3  0.813879  0.507878  0.405821  0.840531
4  0.605386  0.972121  0.126850  0.792573
5  0.821819  0.928974  0.767605  0.514593
6  0.000999  0.424780  0.605551  0.625111
7  0.301698  0.723679  0.354974  0.052045
8  0.895807  0.603437  0.981868  0.352869
9  0.368341  0.766077  0.924654  0.741197

In [44]:
newDf1.drop(['B'],axis = 1,inplace=True)

KeyError: "['B'] not found in axis"

In [45]:
newDf1

C         D         E
0  0.550535  0.004073  0.835947
1  0.799095  0.359194  0.904489
2  0.429532  0.499447  0.103171
3  0.507878  0.405821  0.840531
4  0.972121  0.126850  0.792573
5  0.928974  0.767605  0.514593
6  0.424780  0.605551  0.625111
7  0.723679  0.354974  0.052045
8  0.603437  0.981868  0.352869
9  0.766077  0.924654  0.741197

In [47]:
newDf1.drop(['C'],axis = 1)

D         E
0  0.004073  0.835947
1  0.359194  0.904489
2  0.499447  0.103171
3  0.405821  0.840531
4  0.126850  0.792573
5  0.767605  0.514593
6  0.605551  0.625111
7  0.354974  0.052045
8  0.981868  0.352869
9  0.924654  0.741197

In [48]:
newDf1

C         D         E
0  0.550535  0.004073  0.835947
1  0.799095  0.359194  0.904489
2  0.429532  0.499447  0.103171
3  0.507878  0.405821  0.840531
4  0.972121  0.126850  0.792573
5  0.928974  0.767605  0.514593
6  0.424780  0.605551  0.625111
7  0.723679  0.354974  0.052045
8  0.603437  0.981868  0.352869
9  0.766077  0.924654  0.741197

In [52]:
newDf1.drop([1],axis=0)

KeyError: '[1] not found in axis'

In [51]:
newDf1

C         D         E
0  0.550535  0.004073  0.835947
2  0.429532  0.499447  0.103171
3  0.507878  0.405821  0.840531
4  0.972121  0.126850  0.792573
5  0.928974  0.767605  0.514593
6  0.424780  0.605551  0.625111
7  0.723679  0.354974  0.052045
8  0.603437  0.981868  0.352869
9  0.766077  0.924654  0.741197

In [53]:
newDf1.reset_index(drop = True)

C         D         E
0  0.550535  0.004073  0.835947
1  0.429532  0.499447  0.103171
2  0.507878  0.405821  0.840531
3  0.972121  0.126850  0.792573
4  0.928974  0.767605  0.514593
5  0.424780  0.605551  0.625111
6  0.723679  0.354974  0.052045
7  0.603437  0.981868  0.352869
8  0.766077  0.924654  0.741197

In [3]:
import numpy
a = numpy.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [7]:
print(a.dtype)

int32


In [9]:
a = numpy.array([[1,2],[3,4],[5,6],[7,8],[9,10]],dtype = numpy.float64)
a.itemsize

8

In [10]:
a

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [11]:
a.size

10

In [12]:
a.shape

(5, 2)

In [14]:
a = numpy.array([[1,2],[3,4],[5,6],[7,8],[9,10]],dtype = complex)
a

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j],
       [ 5.+0.j,  6.+0.j],
       [ 7.+0.j,  8.+0.j],
       [ 9.+0.j, 10.+0.j]])

In [16]:
numpy.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
numpy.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
numpy.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
numpy.arange(2,10,3)

array([2, 5, 8])

In [22]:
numpy.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [29]:
b = numpy.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
b.reshape(5,1)

ValueError: cannot reshape array of size 10 into shape (5,1)

In [30]:
b.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
print(b.min())
print(b.max())
print(b.sum())
print(b.sum(axis=0))
print(b.sum(axis=1))

1
10
55
[25 30]
[ 3  7 11 15 19]


In [37]:
numpy.sqrt(b)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974],
       [2.64575131, 2.82842712],
       [3.        , 3.16227766]])

In [38]:
numpy.std(b) #Standard Deviation

2.8722813232690143

In [42]:
x = numpy.array([[1,2],[3,4]])
y = numpy.array([[5,6],[7,8]])


In [43]:
x

array([[1, 2],
       [3, 4]])

In [44]:
y

array([[5, 6],
       [7, 8]])

In [45]:
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x%y)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1 2]
 [3 4]]


In [46]:
x.dot(y)

array([[19, 22],
       [43, 50]])

In [3]:
import pandas as pd
Weather_Data = {
    "Day":["1/1/2023",'2/1/2023','3/1/2023','4/1/2023','5/1/2023','6/1/2023','7/1/2023','8/1/2023',
          '9/1/2023','10/1/2023'],
    "Temperature":['30F','45f','32F','35F','23F','46F','33F','23F','21F','29f'],
    "WindSpeed":[43,65,64,23,76,74,64,74,54,63]
}
output = pd.DataFrame(Weather_Data)
print(out)

         Day Temperature  WindSpeed
0   1/1/2023         30F         43
1   2/1/2023         45f         65
2   3/1/2023         32F         64
3   4/1/2023         35F         23
4   5/1/2023         23F         76
5   6/1/2023         46F         74
6   7/1/2023         33F         64
7   8/1/2023         23F         74
8   9/1/2023         21F         54
9  10/1/2023         29f         63


In [5]:
#DF.to_csv('players1.csv', index=False)
output = pd.DataFrame(Weather_Data)
output.to_csv('Weather_Data.csv',index=False)

In [8]:
output.head(2)

Day Temperature  WindSpeed
0  1/1/2023         30F         43
1  2/1/2023         45f         65

In [11]:
date = pd.read_csv("Weather_Data.csv", parse_dates=["day"]) 

ValueError: Missing column provided to 'parse_dates': 'day'